### PR TITLE
adding Enum type

### PR DESCRIPTION
**Pull request by mattdesl**
Including a Java-like Enum

### CODE REVIEW

**Comment by mattdesl** [comment]
Builds for different module patterns would be awesome. I'll add some docs for Enum at some point soon

**Comment by dsherret** [comment]
You can do something like this for a no module pattern:

```
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define([], factory);
    } else {
        // Browser globals
        root.Class = factory();
    }
}(this, function () {
    // code for jsOOP goes here

    return Class;
}));
```

**Comment by mikkoh** [comment]
@dhsto That's actually quite nice. I like it. I was thinking of a much yuckier syntax via Grunt and building via Grunt. Thanks for sharing that.

**Comment by mattdesl** [comment]
looks like browserify can generate UMD (similar to dhsto's snippet) with the `--standalone` option. 
http://killdream.github.io/2013/06/06/node-modules-to-rule-them-all.html

**Review by AnuchaRodpha — APPROVED** [review]

**Pull request merged**
